#! /usr/bin/env ruby

require 'rubygems'

host_name = ARGV[0]
domain_name = ARGV[1]

walk = `snmpwalk -c public -v 1 -Ofn #{host_name} .1.3.6.1.4.1.32919.4.2.1.1.1.1.2`
walk.strip!

host_running_domain = walk.split(/\n/).detect do |line|
  oid, data = *line.split(/\=/, 2)
  oid.strip!
  data.strip!
  datatype, value = data.split(/:/, 2)
  datatype.strip!
  value.strip!
  value.gsub!(/^\"/, '')
  value.gsub!(/\"$/, '')
  oid_match = oid =~ /\.1\.3\.6\.1\.4\.1\.32919\.4\.2\.1\.1\.1\.1\.2\.\d+\.1/
  oid_match && value == domain_name
end

if host_running_domain
  puts "HOST OK: #{domain_name} found on #{host_name}"
  exit 0
else
  puts "HOST CRITICAL: #{domain_name} was not found on #{host_name}"
  exit 2
end