#! /usr/bin/env ruby

require 'rubygems'

host_name = ARGV[0]
domain_name = ARGV[1]
user_name = ARGV[2]

walk = `snmpwalk -c public -v 1 -Ofn #{host_name} .1.3.6.1.4.1.32919.4.2.2.1.1.2`
walk.strip!

shell_users = walk.split(/\n/).map do |line|
  oid, data = *line.split(/\=/, 2)
  oid.strip!
  data.strip!
  datatype, value = data.split(/:/, 2)
  datatype.strip!
  value.strip!
  value.gsub!(/^\"/, '')
  value.gsub!(/\"$/, '')
  value if oid =~ /^.1.3.6.1.4.1.32919.4.2.2.1.1.2.\d+.2.1.\d+$/
end.compact.uniq

if shell_users.include?(user_name)
  puts "XEN SHELL USER OK: #{user_name} allowed to access Xen shell for #{domain_name}"
  exit 0
else
  puts "XEN SHELL USER CRITICAL: #{user_name} not on Xen shell access list for #{domain_name}"
  exit 2
end